---
http_interactions:
- request:
    method: post
    uri: https://mws.amazonservices.com/Products/2011-10-01
    body:
      encoding: UTF-8
      string: AWSAccessKeyId=AKIAIVHVPRCMH5UWD4HA&Action=GetMatchingProductForId&IdList.Id.1=035585800158&IdType=UPC&MWSAuthToken=amzn.mws.6eb293fe-7935-feb0-f562-4c4650cff837&MarketplaceId=ATVPDKIKX0DER&SellerId=AAQHWTH7HF8BV&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2021-06-04T16%3A05%3A01Z&Version=2011-10-01&Signature=gZwr6bHDtzNmU3Q%2BOuZ0NEgum02%2F9wjyZwhREtLKLxA%3D
    headers:
      User-Agent:
      - Jeff/2.0.2 (Language=Ruby; vm1396606)
      Content-Type:
      - application/x-www-form-urlencoded; charset=UTF-8
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - Server
      Date:
      - Fri, 04 Jun 2021 16:05:02 GMT
      Content-Type:
      - text/xml
      Content-Length:
      - '5702'
      Connection:
      - keep-alive
      X-Amz-Rid:
      - QJWE45TTVJB3HBKMX2FV
      X-Mws-Quota-Max:
      - '18000.0'
      X-Mws-Quota-Remaining:
      - '18000.0'
      X-Mws-Quota-Resetson:
      - '2021-06-04T16:32:00.000Z'
      X-Amz-Date:
      - Fri, 04 Jun 2021 16:05:02 GMT
      X-Mws-Request-Id:
      - 92a30ebb-cd2f-41a4-9241-87a6414a405c
      X-Mws-Timestamp:
      - '2021-06-04T16:05:02.113Z'
      X-Mws-Response-Context:
      - LxW6TL7t8+Gao5KYvDcRcov6mlbQkznfhdmi5Re+rWMkDcDfwMTfdnklXCRy7lIjz5ocqSEJ3kw=
      Vary:
      - accept-encoding,Content-Type,Accept-Encoding,X-Amzn-CDN-Cache,X-Amzn-AX-Treatment,User-Agent
      Permissions-Policy:
      - interest-cohort=()
    body:
      encoding: ASCII-8BIT
      string: <?xml version="1.0"?><GetMatchingProductForIdResponse xmlns="http://mws.amazonservices.com/schema/Products/2011-10-01"><GetMatchingProductForIdResult
        Id="035585800158" IdType="UPC" status="Success"><Products xmlns:ns2="http://mws.amazonservices.com/schema/Products/2011-10-01/default.xsd"><Product><Identifiers><MarketplaceASIN><MarketplaceId>ATVPDKIKX0DER</MarketplaceId><ASIN>B005HE1OMW</ASIN></MarketplaceASIN></Identifiers><AttributeSets><ns2:ItemAttributes
        xml:lang="en-US"><ns2:Binding>Misc.</ns2:Binding><ns2:Brand>KONG</ns2:Brand><ns2:ItemDimensions><ns2:Height
        Units="inches">2.70</ns2:Height><ns2:Length Units="inches">8.50</ns2:Length><ns2:Width
        Units="inches">4.30</ns2:Width><ns2:Weight Units="pounds">0.45</ns2:Weight></ns2:ItemDimensions><ns2:Label>Kong</ns2:Label><ns2:ListPrice><ns2:Amount>10.99</ns2:Amount><ns2:CurrencyCode>USD</ns2:CurrencyCode></ns2:ListPrice><ns2:Manufacturer>Kong</ns2:Manufacturer><ns2:Model>382998</ns2:Model><ns2:PackageDimensions><ns2:Height
        Units="inches">2.9133858238</ns2:Height><ns2:Length Units="inches">9.3700787306</ns2:Length><ns2:Width
        Units="inches">5.1968503884</ns2:Width><ns2:Weight Units="pounds">0.44</ns2:Weight></ns2:PackageDimensions><ns2:PackageQuantity>1</ns2:PackageQuantity><ns2:PartNumber>382998</ns2:PartNumber><ns2:ProductGroup>Pet
        Products</ns2:ProductGroup><ns2:ProductTypeName>PET_TOY</ns2:ProductTypeName><ns2:Publisher>Kong</ns2:Publisher><ns2:SmallImage><ns2:URL>https://m.media-amazon.com/images/I/51Xi07T9oaL._SL75_.jpg</ns2:URL><ns2:Height
        Units="pixels">75</ns2:Height><ns2:Width Units="pixels">75</ns2:Width></ns2:SmallImage><ns2:Studio>Kong</ns2:Studio><ns2:Title>Kong
        Company Kong Camo Wubba Large - Wm1</ns2:Title></ns2:ItemAttributes></AttributeSets><Relationships/><SalesRankings><SalesRank><ProductCategoryId>pet_products_display_on_website</ProductCategoryId><Rank>187632</Rank></SalesRank><SalesRank><ProductCategoryId>2975414011</ProductCategoryId><Rank>2079</Rank></SalesRank></SalesRankings></Product><Product><Identifiers><MarketplaceASIN><MarketplaceId>ATVPDKIKX0DER</MarketplaceId><ASIN>B00HYER594</ASIN></MarketplaceASIN></Identifiers><AttributeSets><ns2:ItemAttributes
        xml:lang="en-US"><ns2:Binding>Misc.</ns2:Binding><ns2:Brand>KONG</ns2:Brand><ns2:Label>Kong</ns2:Label><ns2:Manufacturer>Kong</ns2:Manufacturer><ns2:Model>Kong
        Company 292811 Kong Camo Wubba Lg</ns2:Model><ns2:PackageDimensions><ns2:Height
        Units="inches">3</ns2:Height><ns2:Length Units="inches">13</ns2:Length><ns2:Width
        Units="inches">3</ns2:Width><ns2:Weight Units="pounds">1</ns2:Weight></ns2:PackageDimensions><ns2:PackageQuantity>1</ns2:PackageQuantity><ns2:PartNumber>292811</ns2:PartNumber><ns2:ProductGroup>Pet
        Products</ns2:ProductGroup><ns2:ProductTypeName>PET_TOY</ns2:ProductTypeName><ns2:Publisher>Kong</ns2:Publisher><ns2:SmallImage><ns2:URL>https://m.media-amazon.com/images/I/41rJPgyrqPL._SL75_.jpg</ns2:URL><ns2:Height
        Units="pixels">75</ns2:Height><ns2:Width Units="pixels">38</ns2:Width></ns2:SmallImage><ns2:Studio>Kong</ns2:Studio><ns2:Title>KONG
        Company 292811 Camo Wubba Lg</ns2:Title></ns2:ItemAttributes></AttributeSets><Relationships/><SalesRankings/></Product><Product><Identifiers><MarketplaceASIN><MarketplaceId>ATVPDKIKX0DER</MarketplaceId><ASIN>B0018N5328</ASIN></MarketplaceASIN></Identifiers><AttributeSets><ns2:ItemAttributes
        xml:lang="en-US"><ns2:Binding>Misc.</ns2:Binding><ns2:Brand>KONG</ns2:Brand><ns2:Color>Assorted
        Camo</ns2:Color><ns2:ItemDimensions><ns2:Height Units="inches">3</ns2:Height><ns2:Length
        Units="inches">13</ns2:Length><ns2:Width Units="inches">3</ns2:Width><ns2:Weight
        Units="pounds">0.41</ns2:Weight></ns2:ItemDimensions><ns2:IsAdultProduct>false</ns2:IsAdultProduct><ns2:IsAutographed>false</ns2:IsAutographed><ns2:IsMemorabilia>false</ns2:IsMemorabilia><ns2:Label>KONG</ns2:Label><ns2:Languages><ns2:Language><ns2:Name>english</ns2:Name><ns2:Type>Unknown</ns2:Type></ns2:Language></ns2:Languages><ns2:ListPrice><ns2:Amount>10.59</ns2:Amount><ns2:CurrencyCode>USD</ns2:CurrencyCode></ns2:ListPrice><ns2:Manufacturer>KONG</ns2:Manufacturer><ns2:MaterialType>Durable
        reinforced nylon fabric</ns2:MaterialType><ns2:Model>WM1</ns2:Model><ns2:NumberOfItems>1</ns2:NumberOfItems><ns2:PackageDimensions><ns2:Height
        Units="inches">1.199999998776</ns2:Height><ns2:Length Units="inches">13.99999998572</ns2:Length><ns2:Width
        Units="inches">3.99999999592</ns2:Width><ns2:Weight Units="pounds">0.44974301448</ns2:Weight></ns2:PackageDimensions><ns2:PackageQuantity>1</ns2:PackageQuantity><ns2:PartNumber>WM1</ns2:PartNumber><ns2:ProductGroup>Pet
        Products</ns2:ProductGroup><ns2:ProductTypeName>PET_TOY</ns2:ProductTypeName><ns2:Publisher>KONG</ns2:Publisher><ns2:Size>Large</ns2:Size><ns2:SmallImage><ns2:URL>https://m.media-amazon.com/images/I/41kYzQ+R-dL._SL75_.jpg</ns2:URL><ns2:Height
        Units="pixels">75</ns2:Height><ns2:Width Units="pixels">62</ns2:Width></ns2:SmallImage><ns2:Studio>KONG</ns2:Studio><ns2:Title>KONG
        Camo Wubba Dog Toy - Large (Assorted Colors)</ns2:Title><ns2:Warranty>Guarantee
        against manufacturer defect.</ns2:Warranty></ns2:ItemAttributes></AttributeSets><Relationships><VariationParent><Identifiers><MarketplaceASIN><MarketplaceId>ATVPDKIKX0DER</MarketplaceId><ASIN>B002Y5X7E0</ASIN></MarketplaceASIN></Identifiers></VariationParent></Relationships><SalesRankings><SalesRank><ProductCategoryId>pet_products_display_on_website</ProductCategoryId><Rank>35798</Rank></SalesRank><SalesRank><ProductCategoryId>2975419011</ProductCategoryId><Rank>738</Rank></SalesRank></SalesRankings></Product></Products></GetMatchingProductForIdResult><ResponseMetadata><RequestId>92a30ebb-cd2f-41a4-9241-87a6414a405c</RequestId></ResponseMetadata></GetMatchingProductForIdResponse>
  recorded_at: Fri, 04 Jun 2021 16:05:02 GMT
recorded_with: VCR 6.0.0
