RSpec/NestedGroups:
  Max: 4
RSpec/MultipleExpectations:
  Exclude:
    - "spec/**/*"
RSpec/ExampleLength:
  Exclude:
    - "spec/**/*"
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
