FROM ubuntu:20.04

# ARG BUILD_APT_DEPS="ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip git binutils"
# ARG DEBIAN_FRONTEND=noninteractive
# ARG TARGET=stable

# RUN apt update && apt upgrade -y && \
#   apt install -y ${BUILD_APT_DEPS} && \
#   git clone https://github.com/neovim/neovim.git /tmp/neovim && \
#   cd /tmp/neovim && \
# 	git checkout tags/${TARGET} && \
#   make CMAKE_BUILD_TYPE=Release && \
#   make CMAKE_INSTALL_PREFIX=/usr/local install && \
#   strip /usr/local/bin/nvim && \
#   cd ~ && \
#   rm -rf /tmp/neovim && \
#   apt purge -y ${BUILD_APT_DEPS} && apt autoremove -y --purge

# CMD ["/usr/local/bin/nvim"]
# WORKDIR /tmp/neovim
#
# RUN apt-get update && apt upgrade -y 
# ARG BUILD_APT_DEPS="curl git ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip binutils"
# ARG DEBIAN_FRONTEND=noninteractive
# RUN apt-get install -yq ${BUILD_APT_DEPS}

# RUN curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
# RUN chmod u+x nvim.appimage
# RUN ./nvim.appimage --appimage-extract
# RUN ./squashfs-root/AppRun --version
# RUN ln -s /squashfs-root/AppRun /usr/bin/nvim

# RUN apt-get update -qq
# RUN apt-get install software-properties-common -yq

# RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
# RUN apt-add-repository https://cli.github.com/packages
# RUN apt-get update -qq
# RUN apt-get install gh

# # RUN add-apt-repository ppa:deadsnakes/ppa
# # RUN apt-get update -qq
# RUN apt-get install python3.9 -yq
# RUN apt-get install tmux -yq

# RUN apt-get install exuberant-ctags

# RUN git clone https://github.com/Lichers0/nvim.git ~/.nv-ide
# RUN mkdir -p ~/.config/nvim
# RUN cp ~/.nv-ide/lua/plugins.lua ~/.config/nvim/init.lua
# RUN nvim --headless +:PackerInstall +qa
# RUN nvim --headless +PackerInstall +qa
# RUN rm ~/.config/nvim/init.lua
# RUN rm -rf ~/.config/nvim
# RUN ln -s ~/.nv-ide ~/.config/nvim


# WORKDIR /app
